//get all 

GET http://localhost:5001/courses

###
// request for sortone
GET http://localhost:5001/courses/60c1ac974bf29732796b4612


###

// add data to schema

POST  http://localhost:5001/courses
Content-Type: application/json

{
    
    "name":"Printing Technology",
    "noYear":"1 years",
    "totalPaper":"32",
    "description":"happy to learning"

}


### 

// schema delete

DELETE http://localhost:5001/courses/60d97073efe168dc6acb3084

### 

// update schema


PUT http://localhost:5001/courses/60d96ed29e1059d7a24fd9a4
Content-Type: application/json
{
    "name":"Printing Technology",
    "noYear":"1 years",
    "totalPaper":"32",
    "description":"happy to learning"
}