// get all teachers


GET  http://localhost:5001/teachers


###

//create Dpeartment

POST http://localhost:5001/teachers
Content-Type: application/json

{
    "tname":"been",
    "department":"elctroinics Engineering Department"

}

###

// sort a department using id

GET http://localhost:5001/teachers/60c34dd997eec28b90665d34

### 

// update schema

PUT  http://localhost:5001/teachers/60d02e90814a011d88a6508b
Content-Type: application/json

{
    "tname":"doras",
    "department": "Computer Engineering Departments"

}


### 

// schema delete

DELETE http://localhost:5001/teachers/60cee887df13dd1d50ce8336

### 
